export const cardapio = {
    categorias: {
        tradicional: [
        { id: 1, sabor: "alho e oleo" },
        { id: 2, sabor: "calabresa" },
        { id: 3, sabor: "frango" },
        { id: 4, sabor: "lombinho" },
        { id: 5, sabor: "milho verde" },
        { id: 6, sabor: "escarola" },
        { id: 7, sabor: "marguerita" },
        { id: 8, sabor: "mussarela" },
        { id: 9, sabor: "parmegiana" },
        { id: 10, sabor: "presunto" }
    ],
        especial: [
        { id: 11, sabor: "rustica" },
        { id: 12, sabor: "canadense" },
        { id: 13, sabor: "crocante" },
        { id: 14, sabor: "americana" },
        { id: 15, sabor: "havaiana" },
        { id: 16, sabor: "palmito" },
        { id: 17, sabor: "caipira" },
        { id: 18, sabor: "atum" },
        { id: 19, sabor: "vegetariana" },
        { id: 20, sabor: "curitiba" },
        { id: 21, sabor: "mexicana" },
        { id: 22, sabor: "calabresa especial" },
        { id: 23, sabor: "escarola c/bacon" },
        { id: 24, sabor: "bacon" },
        { id: 25, sabor: "da casa" },
        { id: 26, sabor: "napolitana" },
        { id: 27, sabor: "carioca" },
        { id: 28, sabor: "marinara" },
        { id: 29, sabor: "brocolis c/bacon" },
        { id: 30, sabor: "siciliana" },
        { id: 31, sabor: "espanhola" },
        { id: 32, sabor: "milho c/bacon" },
        { id: 33, sabor: "bolonhesa" },
        { id: 34, sabor: "brasileira" },
        { id: 35, sabor: "frango c/catupiry" },
        { id: 36, sabor: "paulista" },
        { id: 37, sabor: "quatro queijos" },
        { id: 38, sabor: "portuguesa" },
        { id: 39, sabor: "palmito c/bacon" },
        { id: 40, sabor: 'Calabresa com cebola'},
        { id: 41, sabor: 'Calabresa com catupiry'},
        { id: 42, sabor: 'Frango cheddar'},
        { id: 43, sabor: 'Calabresa com cheddar '},
        { id: 44, sabor: 'Lombo com cheddar'},
        { id: 45, sabor: 'Lombo catupiry'},
        { id: 46, sabor: 'Lombo especial '},
        { id: 47, sabor: 'Bauru '},
        { id: 48, sabor: 'Baiana '},
        { id: 49, sabor: '2 queijos'},
        { id: 50, sabor: 'Calafrango '},
        { id: 51, sabor: 'Franpalha '},
        { id: 52, sabor: 'Calabresa com bacon'},
    ],
        premium: [
        { id: 40, sabor: "tomate seco" },
        { id: 41, sabor: "peperoni" },
        { id: 42, sabor: "peito de peru" },
        { id: 43, sabor: "nachos" },
        { id: 44, sabor: "strogonof de carne" },
        { id: 45, sabor: "mignon c/alho" },
        { id: 46, sabor: "mignon c/catupiry" },
        { id: 47, sabor: "mignon c/cheddar" },
        { id: 48, sabor: "mignon barbecue" }
    ],
        doces: [
        { id: 49, sabor: "chocolate preto" },
        { id: 50, sabor: "chocolate branco" },
        { id: 51, sabor: "sonho de valsa" },
        { id: 52, sabor: "ouro branco" },
        { id: 53, sabor: "banana" },
        { id: 54, sabor: "charge" },
        { id: 55, sabor: "beijinho" },
        { id: 56, sabor: "dois amores" },
        { id: 57, sabor: "prestigio" },
        { id: 58, sabor: "brigadeiro" },
        { id: 59, sabor: "romeu e julieta" },
        { id: 60, sabor: "choconana" },
        { id:61, sabor: 'Sensação de morando'} ,
        { id:62, sabor: 'Sensação uva'},
        { id:63, sabor: 'Ninho com Nutella'},
        { id:64, sabor: 'Twix'},
        { id:65, sabor: 'Laka Oreo' },
        { id:66, sabor: 'Banana nevada' },
        { id:67, sabor: 'Confete '},
        { id:68, sabor: 'Banoff '},
        { id:69, sabor: 'Paçoquinha'},
        { id:70, sabor: 'Marshmallow'},
    ]
}
};


